### ISSUE TITLE
I need a screenshot

### ISSUE THREAD

**Issue by xbsonmez** [buraksonmez1/blogy#1]

**Comment by buraksonmez1** [comment]
![adsiz2](https://user-images.githubusercontent.com/42543196/53302746-bf64eb00-3872-11e9-9b84-cd569a8935e9.jpg)

![adsiz3](https://user-images.githubusercontent.com/42543196/53302747-bf64eb00-3872-11e9-8320-5acb6aadfbb1.jpg)


![adsiz](https://user-images.githubusercontent.com/42543196/53302748-bf64eb00-3872-11e9-8de3-f4fddcd15698.jpg)
